name = "borel"
main = "functions/_redirect-www.js"
compatibility_date = "2025-01-01"

[site]
bucket = "./"
entry-point = "functions"

[build]
command = ""

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }