name = "borel"
compatibility_date = "2025-01-01"

[site]
bucket = "."              # vše je teď v rootu
entry-point = "functions"

[build]
command = ""

# Výstupní složka pro Pages
pages_build_output_dir = "."

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }

[observability]
logs = true
