name = "borel"
compatibility_date = "2025-01-01"

# === Cloudflare Pages konfigurace ===
pages_build_output_dir = "./"        # root slo≈æka projektu (HTML, CSS, JS)

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }